### ISSUE TITLE
Updating the Quickstart page description 

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#59] opened 2019-08-11 01:16 UTC
Updating the description to clarify the issue with 30 days deletion (including when account in provided).
I am not sure where is the code for that.

**Comment by mwang87** [comment] 2019-08-11 01:28
Duplicate of https://github.com/mwang87/GNPS_quickstart/issues/7

**Comment by mwang87** [comment] 2019-09-03 20:42
@klj0019 Any updates on this?

**Comment by klj0019** [comment] 2019-09-03 20:45
I thought I had finished this update. Was with the last pull request? Did I miss something?

**Comment by mwang87** [comment] 2019-09-03 20:45
Can you please link the PR here and bump the PR saying its ready to be reviewed?

**Comment by mwang87** [comment] 2019-09-16 23:49
These issues will need to be revisited as we are changing upload policy.

**Closed by mwang87** 2019-09-16 23:49 UTC
Labels: help wanted
